import React, { useEffect, useState } from 'react';
import { apiService } from '../../services/api';
import { useToast } from '../../hooks/useToast';
import { Card } from '../../components/common/Card';
import { Badge } from '../../components/common/Badge';
import { Button } from '../../components/common/Button';
import { Input } from '../../components/common/Input';
import { Spinner } from '../../components/common/Spinner';
import {
  FileCheck2,
  Printer,
  Download,
  Save,
  RotateCcw,
  Plus,
  Trash2,
  ExternalLink,
  Github,
  Linkedin,
  Globe,
  Mail,
  Phone,
  MapPin,
  Sparkles,
} from 'lucide-react';

export const ResumeBuilder = () => {
  const { showSuccess, showError } = useToast();
  const [resume, setResume] = useState(null);
  const [profile, setProfile] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  // Resume form state
  const [resumeData, setResumeData] = useState({
    headline: '',
    summary: '',
    target_role: '',
    education: [],
    skills: [],
    projects: [],
    experience: [],
    certifications: [],
    achievements: [],
    links: { github: '', linkedin: '', portfolio: '' },
  });

  const [skillInput, setSkillInput] = useState('');
  const [activeTab, setActiveTab] = useState('preview'); // 'edit' | 'preview'

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      setLoading(true);
      const [resRes, profRes] = await Promise.all([
        apiService.getStudentResume(),
        apiService.getStudentFullProfile(),
      ]);
      setResume(resRes);
      setProfile(profRes);
      setResumeData(resRes.data);
    } catch (err) {
      showError('Failed to load resume information.');
    } finally {
      setLoading(false);
    }
  };

  const handleSaveResume = async () => {
    try {
      setSaving(true);
      const updated = await apiService.updateStudentResume(resumeData);
      setResume(updated);
      showSuccess('Resume updated successfully!');
    } catch (err) {
      showError('Failed to save resume changes.');
    } finally {
      setSaving(false);
    }
  };

  const handleAddSkill = (e) => {
    e.preventDefault();
    if (!skillInput.trim()) return;
    if (!resumeData.skills.includes(skillInput.trim())) {
      setResumeData({ ...resumeData, skills: [...resumeData.skills, skillInput.trim()] });
    }
    setSkillInput('');
  };

  const handleRemoveSkill = (skillToRemove) => {
    setResumeData({
      ...resumeData,
      skills: resumeData.skills.filter((s) => s !== skillToRemove),
    });
  };

  const handleExportPDF = () => {
    window.print();
  };

  const [aiSuggestions, setAiSuggestions] = useState(null);
  const [optimizing, setOptimizing] = useState(false);

  const handleRunAIOptimizer = async () => {
    try {
      setOptimizing(true);
      const res = await apiService.getAIResumeSuggestions(resumeData.target_role || 'Full Stack Engineer', resumeData.summary);
      setAiSuggestions(res);
      showSuccess(`ATS Resume critique generated by ${res.ai_meta?.model_used || 'Gemini 1.5'}!`);
    } catch (err) {
      showError('Failed to run AI resume optimization.');
    } finally {
      setOptimizing(false);
    }
  };

  const applyAISummary = () => {
    if (aiSuggestions?.enhanced_summary_draft) {
      setResumeData({ ...resumeData, summary: aiSuggestions.enhanced_summary_draft });
      showSuccess('AI-enhanced summary applied to resume!');
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '50vh' }}>
        <Spinner size="lg" />
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Top Action Toolbar */}
      <div
        className="no-print"
        style={{
          background: 'linear-gradient(135deg, rgba(30, 41, 59, 0.9) 0%, rgba(15, 23, 42, 0.9) 100%)',
          borderRadius: 'var(--radius-lg)',
          border: '1px solid rgba(255, 255, 255, 0.08)',
          padding: '1.25rem 1.5rem',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '1rem',
        }}
      >
        <div>
          <h1 style={{ fontSize: '1.4rem', fontWeight: 800, color: '#ffffff' }}>Professional Resume Builder</h1>
          <p style={{ color: '#94a3b8', fontSize: '0.85rem', marginTop: '0.2rem' }}>
            ATS-ready layout tailored for industry placement and internship applications.
          </p>
        </div>

        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', flexWrap: 'wrap' }}>
          <button
            onClick={handleRunAIOptimizer}
            disabled={optimizing}
            style={{
              padding: '0.5rem 1rem',
              borderRadius: 'var(--radius-md)',
              border: 'none',
              background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
              color: '#ffffff',
              fontWeight: 700,
              fontSize: '0.8rem',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '0.4rem',
              boxShadow: '0 4px 12px rgba(99, 102, 241, 0.3)',
            }}
          >
            <Sparkles size={14} /> {optimizing ? 'Analyzing with AI...' : 'AI ATS Optimizer'}
          </button>

          <div style={{ display: 'flex', background: 'rgba(255,255,255,0.05)', borderRadius: 'var(--radius-md)', padding: '2px' }}>
            <button
              onClick={() => setActiveTab('preview')}
              style={{
                padding: '0.4rem 0.85rem',
                borderRadius: 'var(--radius-sm)',
                border: 'none',
                background: activeTab === 'preview' ? '#14b8a6' : 'transparent',
                color: activeTab === 'preview' ? '#ffffff' : '#94a3b8',
                fontWeight: 600,
                fontSize: '0.8rem',
                cursor: 'pointer',
              }}
            >
              Resume Preview
            </button>
            <button
              onClick={() => setActiveTab('edit')}
              style={{
                padding: '0.4rem 0.85rem',
                borderRadius: 'var(--radius-sm)',
                border: 'none',
                background: activeTab === 'edit' ? '#14b8a6' : 'transparent',
                color: activeTab === 'edit' ? '#ffffff' : '#94a3b8',
                fontWeight: 600,
                fontSize: '0.8rem',
                cursor: 'pointer',
              }}
            >
              Edit Content
            </button>
          </div>

          <Button variant="secondary" size="sm" onClick={handleExportPDF}>
            <Download size={14} /> Export PDF
          </Button>
          <Button variant="primary" size="sm" onClick={handleSaveResume} disabled={saving}>
            <Save size={14} /> {saving ? 'Saving...' : 'Save Draft'}
          </Button>
        </div>
      </div>

      {/* AI Resume Feedback Banner */}
      {aiSuggestions && (
        <div
          className="no-print"
          style={{
            padding: '1.25rem',
            background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.1) 0%, rgba(15, 23, 42, 0.8) 100%)',
            border: '1px solid rgba(129, 140, 248, 0.4)',
            borderRadius: 'var(--radius-lg)',
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Sparkles size={16} color="#818cf8" />
              <span style={{ fontWeight: 800, color: '#ffffff', fontSize: '0.95rem' }}>
                AI ATS Score: <span style={{ color: '#10b981' }}>{aiSuggestions.overall_ats_score}/100</span>
              </span>
            </div>
            <span style={{ fontSize: '0.75rem', color: '#94a3b8', fontFamily: 'monospace' }}>
              Engine: {aiSuggestions.ai_meta?.model_used}
            </span>
          </div>

          <p style={{ fontSize: '0.8rem', color: '#cbd5e1', marginBottom: '0.75rem' }}>
            {aiSuggestions.summary_critique}
          </p>

          <div style={{ background: 'rgba(255, 255, 255, 0.03)', padding: '0.85rem', borderRadius: 'var(--radius-md)', border: '1px solid rgba(255,255,255,0.08)' }}>
            <div style={{ fontSize: '0.75rem', fontWeight: 700, color: '#818cf8', marginBottom: '0.25rem' }}>
              Recommended ATS Summary Draft:
            </div>
            <p style={{ fontSize: '0.8rem', color: '#ffffff', fontStyle: 'italic' }}>
              "{aiSuggestions.enhanced_summary_draft}"
            </p>
            <button
              onClick={applyAISummary}
              style={{
                marginTop: '0.5rem',
                padding: '0.35rem 0.75rem',
                background: '#10b981',
                color: '#ffffff',
                border: 'none',
                borderRadius: 'var(--radius-sm)',
                fontSize: '0.75rem',
                fontWeight: 700,
                cursor: 'pointer',
              }}
            >
              ✓ Apply to Resume Summary
            </button>
          </div>
        </div>
      )}

      {/* Main Content View (Edit or Live Preview) */}
      {activeTab === 'edit' ? (
        <div className="no-print grid-responsive grid-cols-2" style={{ gap: '1.5rem' }}>
          <Card title="Header & Objective">
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <Input
                label="Headline / Title"
                value={resumeData.headline}
                onChange={(e) => setResumeData({ ...resumeData, headline: e.target.value })}
              />
              <Input
                label="Target Role"
                value={resumeData.target_role}
                onChange={(e) => setResumeData({ ...resumeData, target_role: e.target.value })}
              />
              <div>
                <label className="label">Executive Summary</label>
                <textarea
                  className="input"
                  rows={4}
                  value={resumeData.summary}
                  onChange={(e) => setResumeData({ ...resumeData, summary: e.target.value })}
                  style={{ resize: 'vertical' }}
                />
              </div>
            </div>
          </Card>

          <Card title="Skills & Links">
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div>
                <label className="label">Add Skill to Resume</label>
                <form onSubmit={handleAddSkill} style={{ display: 'flex', gap: '0.5rem' }}>
                  <Input
                    placeholder="e.g. React, Python, Docker"
                    value={skillInput}
                    onChange={(e) => setSkillInput(e.target.value)}
                  />
                  <Button type="submit" variant="secondary" size="sm">
                    <Plus size={14} />
                  </Button>
                </form>
                <div style={{ display: 'flex', gap: '0.35rem', flexWrap: 'wrap', marginTop: '0.75rem' }}>
                  {resumeData.skills.map((s, i) => (
                    <span
                      key={i}
                      style={{
                        fontSize: '0.75rem',
                        background: 'rgba(20,184,166,0.15)',
                        color: '#14b8a6',
                        padding: '2px 8px',
                        borderRadius: '4px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px',
                      }}
                    >
                      {s}
                      <button
                        onClick={() => handleRemoveSkill(s)}
                        style={{ background: 'none', border: 'none', color: '#f87171', cursor: 'pointer', padding: 0 }}
                      >
                        ×
                      </button>
                    </span>
                  ))}
                </div>
              </div>

              <div className="grid-responsive grid-cols-2" style={{ gap: '0.75rem' }}>
                <Input
                  label="GitHub URL"
                  value={resumeData.links?.github || ''}
                  onChange={(e) => setResumeData({ ...resumeData, links: { ...resumeData.links, github: e.target.value } })}
                />
                <Input
                  label="LinkedIn URL"
                  value={resumeData.links?.linkedin || ''}
                  onChange={(e) => setResumeData({ ...resumeData, links: { ...resumeData.links, linkedin: e.target.value } })}
                />
              </div>
            </div>
          </Card>
        </div>
      ) : null}

      {/* Styled Printable A4 Resume Sheet */}
      <div
        id="resume-printable-area"
        style={{
          maxWidth: '850px',
          margin: '0 auto',
          background: '#ffffff',
          color: '#1e293b',
          borderRadius: '4px',
          boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.4)',
          padding: '2.5rem 3rem',
          fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
          lineHeight: 1.5,
        }}
      >
        {/* Printable Header */}
        <div style={{ borderBottom: '2px solid #0f172a', paddingBottom: '1.25rem', marginBottom: '1.25rem' }}>
          <h1 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#0f172a', letterSpacing: '-0.5px' }}>
            {profile?.full_name || 'Aarav Sharma'}
          </h1>
          <div style={{ fontSize: '1rem', fontWeight: 600, color: '#0d9488', marginTop: '0.2rem' }}>
            {resumeData.headline || 'Aspiring Software & Systems Engineer'}
          </div>

          <div
            style={{
              display: 'flex',
              flexWrap: 'wrap',
              gap: '1rem',
              fontSize: '0.8rem',
              color: '#475569',
              marginTop: '0.6rem',
            }}
          >
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
              <Mail size={13} /> {profile?.email}
            </span>
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
              <Phone size={13} /> {profile?.phone || '+91 9876543210'}
            </span>
            <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
              <MapPin size={13} /> {profile?.location || 'New Delhi, India'}
            </span>
            {resumeData.links?.github && (
              <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                <Github size={13} /> {resumeData.links.github}
              </span>
            )}
            {resumeData.links?.linkedin && (
              <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                <Linkedin size={13} /> {resumeData.links.linkedin}
              </span>
            )}
          </div>
        </div>

        {/* Professional Summary */}
        <div style={{ marginBottom: '1.25rem' }}>
          <h2 style={{ fontSize: '0.9rem', fontWeight: 800, textTransform: 'uppercase', color: '#0f172a', letterSpacing: '0.5px', borderBottom: '1px solid #e2e8f0', paddingBottom: '0.25rem', marginBottom: '0.5rem' }}>
            Professional Summary
          </h2>
          <p style={{ fontSize: '0.85rem', color: '#334155', textAlign: 'justify' }}>
            {resumeData.summary}
          </p>
        </div>

        {/* Education */}
        <div style={{ marginBottom: '1.25rem' }}>
          <h2 style={{ fontSize: '0.9rem', fontWeight: 800, textTransform: 'uppercase', color: '#0f172a', letterSpacing: '0.5px', borderBottom: '1px solid #e2e8f0', paddingBottom: '0.25rem', marginBottom: '0.5rem' }}>
            Education
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.6rem' }}>
            {profile?.education?.length > 0 ? (
              profile.education.map((edu, idx) => (
                <div key={idx} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
                  <div>
                    <strong style={{ color: '#0f172a' }}>{edu.degree} - {edu.field_of_study}</strong>
                    <div style={{ color: '#64748b' }}>{edu.institution}</div>
                  </div>
                  <div style={{ textAlign: 'right', color: '#475569' }}>
                    <div>{edu.start_year} - {edu.end_year || 'Present'}</div>
                    {edu.grade_or_cgpa && <div style={{ fontWeight: 600, color: '#0d9488' }}>CGPA: {edu.grade_or_cgpa}</div>}
                  </div>
                </div>
              ))
            ) : (
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
                <div>
                  <strong style={{ color: '#0f172a' }}>{profile?.program || 'B.Tech Computer Science and Engineering'}</strong>
                  <div style={{ color: '#64748b' }}>{profile?.institution_name || 'IIT Delhi'}</div>
                </div>
                <div style={{ textAlign: 'right', color: '#475569' }}>
                  <div>2023 - 2027</div>
                  <div style={{ fontWeight: 600, color: '#0d9488' }}>CGPA: {profile?.cgpa || '8.8'} / 10</div>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Technical & Core Skills */}
        <div style={{ marginBottom: '1.25rem' }}>
          <h2 style={{ fontSize: '0.9rem', fontWeight: 800, textTransform: 'uppercase', color: '#0f172a', letterSpacing: '0.5px', borderBottom: '1px solid #e2e8f0', paddingBottom: '0.25rem', marginBottom: '0.5rem' }}>
            Technical & Professional Competencies
          </h2>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.4rem' }}>
            {resumeData.skills?.map((s, i) => (
              <span
                key={i}
                style={{
                  fontSize: '0.75rem',
                  fontWeight: 600,
                  background: '#f1f5f9',
                  color: '#0f172a',
                  padding: '3px 8px',
                  borderRadius: '3px',
                  border: '1px solid #cbd5e1',
                }}
              >
                {s}
              </span>
            ))}
          </div>
        </div>

        {/* Projects */}
        <div style={{ marginBottom: '1.25rem' }}>
          <h2 style={{ fontSize: '0.9rem', fontWeight: 800, textTransform: 'uppercase', color: '#0f172a', letterSpacing: '0.5px', borderBottom: '1px solid #e2e8f0', paddingBottom: '0.25rem', marginBottom: '0.5rem' }}>
            Key Projects & Portfolios
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {profile?.projects?.map((proj, idx) => (
              <div key={idx} style={{ fontSize: '0.85rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <strong style={{ color: '#0f172a' }}>{proj.title}</strong>
                  {proj.technologies?.length > 0 && (
                    <span style={{ fontSize: '0.75rem', color: '#64748b', fontStyle: 'italic' }}>
                      ({proj.technologies.join(', ')})
                    </span>
                  )}
                </div>
                <p style={{ color: '#334155', margin: '0.2rem 0 0 0', fontSize: '0.8rem' }}>
                  {proj.description}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Certifications & Achievements Grid */}
        <div style={{ display: 'flex', gap: '2rem', flexWrap: 'wrap' }}>
          {profile?.certifications?.length > 0 && (
            <div style={{ flex: 1, minWidth: '220px' }}>
              <h2 style={{ fontSize: '0.9rem', fontWeight: 800, textTransform: 'uppercase', color: '#0f172a', letterSpacing: '0.5px', borderBottom: '1px solid #e2e8f0', paddingBottom: '0.25rem', marginBottom: '0.5rem' }}>
                Certifications
              </h2>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem', fontSize: '0.8rem' }}>
                {profile.certifications.map((c, i) => (
                  <div key={i}>
                    <strong style={{ color: '#0f172a' }}>{c.name}</strong>
                    <div style={{ color: '#64748b' }}>{c.issuer} ({c.issue_year})</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {profile?.achievements?.length > 0 && (
            <div style={{ flex: 1, minWidth: '220px' }}>
              <h2 style={{ fontSize: '0.9rem', fontWeight: 800, textTransform: 'uppercase', color: '#0f172a', letterSpacing: '0.5px', borderBottom: '1px solid #e2e8f0', paddingBottom: '0.25rem', marginBottom: '0.5rem' }}>
                Honors & Achievements
              </h2>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem', fontSize: '0.8rem' }}>
                {profile.achievements.map((a, i) => (
                  <div key={i}>
                    <strong style={{ color: '#0f172a' }}>{a.title}</strong>
                    <div style={{ color: '#64748b' }}>{a.organization} ({a.year})</div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
